### PR TITLE
fix(form-builder): replace prismjs with highlight.js

### LINKED ISSUE #1864: Documentation code snippet visibility problem
When using Firefox with the default dark theme provided by Mozilla the code snippets in the documentation becomes unreadable.
Firefox version 98.0
Mozilla dark theme version 1.2
image

### PR DESCRIPTION
**Pull request by Yelinz**
This is to prevent them from clashing in the addon docs, as they use the
same tags.

How the form-builder editors with highlighting look like now
image
image

fixes #1864

### CODE REVIEW

**Comment by Yelinz** [comment]
Documentation looks normal now aswell
image

File: packages/form-builder/addon/components/cfb-code-editor.js [hunk 1]
```diff
@@ -2,11 +2,14 @@ import { action } from "@ember/object";
 import { addObserver } from "@ember/object/observers";
 import Component from "@glimmer/component";
 import { CodeJar } from "codejar";
-import Prism from "prismjs";
+import hljs from "highlight.js/lib/core";
+import json from "highlight.js/lib/languages/json";
+import markdown from "highlight.js/lib/languages/markdown";
+import jexl from "highlightjs-jexl/src/languages/jexl";
```
Comment (anehx) [inline packages/form-builder/addon/components/cfb-code-editor.js:8]: Can we try to get this into `hightlighjs`?

Comment (czosel) [reply packages/form-builder/addon/components/cfb-code-editor.js:8]: Highlight doesn’t accept new languages in its core anymore. One can make PRs that list a new language as supported via a plugin though - I didn’t do that yet because our plugin is still lacking tests. Would love to do that though, but I might not find the time.

**Review by czosel — APPROVED** [review]
Nice! 💯

File: packages/form-builder/addon/components/cfb-code-editor.js (hunk 1 above)
Comment (anehx) [reply packages/form-builder/addon/components/cfb-code-editor.js:8]: Alright, I didn't know that.
